name: TypeDoc

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]

jobs:
  typedoc:
    # Documentation: https://github.com/zakodium/workflows#typedoc
    uses: zakodium/workflows/.github/workflows/typedoc.yml@typedoc-v1
    with:
      entry: 'src/index.ts'
    secrets:
      github-token: ${{ secrets.BOT_TOKEN }}